---
title: "detection_profile"
author: "Kristen Dang"
date: "January 20, 2015"
output: 
  html_document: 
    fig_height: 7
---
```{r}
library('rGithubClient')
source('/Users/kristen/Computing/external_software/rgithubclient_authenticate.R')
library(edgeR)
library(gplots)
sourceRepoFile(sageCode, "rnaseq_analysis_functions.R")
sourceRepoFile(sageCode, "detection_profiling_functions.R")
```

# Get data
```{r}
sourceRepoFile(sageCode, "NIA-AMP-AD/sample_swap_preliminary.R")
```


# Detection analysis of biotypes
```{r}
countsData = list(Mayo=mayoR.dge, MSSM=mssmR.dge,Broad=broadR.dge)
pseudoFracCount = matrix(NA,nrow = 10,ncol = 3)
pseudoFracDetected = c()
for (i in 1:3){
  data.dge = countsData[[i]]
  paloResult = simplifyBiotypeCategories(data.dge,biomart=Hs)
  paloCounts_wdetect = plotNumSamplesDetecting(paloResult$data,minCount = 2)
  paloRegressResults = runRegressionAndPlot(inCounts = paloCounts_wdetect,bioCategoryCounts = paloResult$observedCounts,totalBiotypeCounts = paloResult$totalCounts,inLibSize = data.dge$samples$lib.size)
  quadrantPlot(paloRegressResults,observedBioCounts = paloResult$observedCounts,plotTitle = names(countsData[i]))
  x = which(names(paloResult$observedCounts) == "pseudogene")
  pseudoFracDetected[i] = paloResult$observedCounts[x] / sum(paloResult$observedCounts)
  pseudoFracCount[,i] = colSums(paloCounts_wdetect[which(paloCounts_wdetect$biotype == "pseudogene"),1:10]) / colSums(paloCounts_wdetect[,1:10])
}
names(pseudoFracDetected) = names(countsData)
print(pseudoFracDetected)
boxplot(pseudoFracCount,names = names(countsData),ylim = range(0,0.015),main = "pseudogene fraction of total data")

```



