---
title: "analyze_ACC-PFC_discordance.Rmd"
author: "Kristen Dang"
date: "June 1, 2015"
output: html_document
---

```{r message=FALSE, echo=FALSE}
library(synapseClient)
synapseLogin()
```

## raw discordance
```{r}
discordFile = synGet('syn4519846',downloadFile = TRUE)
discord_total = read.delim(getFileLocation(discordFile), header = TRUE)
discord_matrix = data.matrix(discord_total)
hist(discord_matrix, col = "honeydew", main = "raw discordance")
dim(discord_matrix)
```


```{r}
sitesFile = synGet('syn4519870',downloadFile = TRUE)
sites = read.delim(getFileLocation(sitesFile), header = TRUE)
sites_matrix = data.matrix(sites)
dim(sites_matrix)
hist(sites_matrix, col = "honeydew", main = "number of sites used to calculate")
```

### Making FULL fractional discordance dataset
```{r}
metaFile = synGet("syn2299154",version = 40)
metadata = read.csv(getFileLocation(metaFile), fileEncoding="macintosh")

genoIDs = metadata$DNA_genotyping_report..Genotyping.Sample_ID[match(colnames(discord_matrix), metadata$DLPFC_RNA_isolation..Sample.RNA.ID)]
pfcIDs = metadata$DLPFC_RNA_isolation..Sample.RNA.ID[match(rownames(discord_matrix), metadata$ACC_RNA_isolation..Sample.RNA.ID)]
allPfcIDs = c(as.character(pfcIDs), setdiff(colnames(discord_matrix),pfcIDs))

# Order the samples
ordered_discord = discord_matrix[, match(toupper(allPfcIDs), toupper(colnames(discord_matrix)))]
dim(ordered_discord)
ordered_sites = sites_matrix[, match(toupper(allPfcIDs), toupper(colnames(discord_matrix)))]
dim(ordered_sites)


full_fractional_discord = ordered_discord / ordered_sites
hist(full_fractional_discord, col = "honeydew", main = "full_fractional discordance")
hist(full_fractional_discord, col = "honeydew", xlim = range(0,0.3), breaks = 200, ylim = range(0,200), main = "discordance -- lower tail ")
```


### Self matches, ACC RNA to PFC RNA
```{r}
selfMatches = diag(full_fractional_discord)
names(selfMatches) = rownames(full_fractional_discord)
# How many are NA?
length(which(is.na(selfMatches)))

# For what samples do we lack data about a self match?
sort(setdiff(metadata$ACC_RNA_isolation..Sample.RNA.ID,names(selfMatches)))

hist(selfMatches, col = "honeydew", xlab = "self discordance", breaks = 40)
# Investigating ones that don't match self
# Which RNA samples don't match self genotype
which(selfMatches > 0.17)

# Verify a few particular ones
# First, the two with high missingness in DNA
selfMatches[which(names(selfMatches) == "MSSM_RNA_ACC_22")] # matches self
selfMatches[which(names(selfMatches) == "MSSM_RNA_ACC_270")] # does not match self


# Three of the "mystery 4" for which there is PFC RNA -- didn't match self or non-self DNA or ACC RNA
selfMatches[which(names(selfMatches) == "MSSM_RNA_ACC_25")] # doesn't match self
selfMatches[which(names(selfMatches) == "MSSM_RNA_ACC_71")] # doesn't match self
selfMatches[which(names(selfMatches) == "MSSM_RNA_ACC_87")] # doesn't match self

```


### Non-self matches FULL
```{r}
fullSelfMatches = diag(full_fractional_discord)
temp = cbind(diag(x=fullSelfMatches),matrix(0,nrow=nrow(full_fractional_discord),ncol = ncol(full_fractional_discord)-length(fullSelfMatches)))

nonSelfMatches = full_fractional_discord - temp
hist(nonSelfMatches, col = "honeydew", xlab = "fractional discordance", breaks = 50, ylim = range(0,400))
num_low_discord = apply(nonSelfMatches,MARGIN = 2,function(x){length(intersect(which(x < 0.2),which(x > 0)))})
which(num_low_discord >= 1)
suspectCols = which(num_low_discord >= 1)

for (i in 1:length(suspectCols)){
  print(colnames(nonSelfMatches)[suspectCols[i]])
  print(paste('non-self matches:', intersect(names(which(nonSelfMatches[,suspectCols[i]] < 0.2)), names(which(nonSelfMatches[,suspectCols[i]] > 0))), sep = ' '))  
}

```

