#!/bin/bash
#BSUB -q alloc 
#BSUB -P acc_CommonMind
#BSUB -J gatk
#BSUB -W 48:00
#BSUB -R "rusage[mem=3000]"
#BSUB -n 8
#BSUB -R "span[hosts=1]"
#BSUB -o %J.stdout
#BSUB -e %J.stderr
#BSUB -L /bin/bash

## Overall max RAM is 20 GB

module load java picard gatk samtools/1.0 bcftools R

SAMPLE=$1
THREADS=$2

cd /sc/orga/projects/CommonMind/data/RNA_EDITING

REF=/sc/orga/projects/GCF/REFERENCES/hg19/bwa_index/hg19.fa

EDIT_DIR=/sc/orga/projects/CommonMind/data/RNA_EDITING/tophat_$SAMPLE
if [ ! -d "$EDIT_DIR" ]; then
  mkdir $EDIT_DIR
fi

## Mark duplicates
# Compute: 4G
#if [! -e "$EDIT_DIR/$SAMPLE.sort.dedup.prefilter.bam" ]; then
java -Xmx2g -jar $PICARD_HOME/MarkDuplicates.jar CREATE_INDEX=true VALIDATION_STRINGENCY=SILENT INPUT=/sc/orga/projects/CommonMind/data/FROM_CORE/Production/fastQ/BySample/tophat209.2.2/tophat_$SAMPLE/$SAMPLE.sort.bam OUTPUT=$EDIT_DIR/$SAMPLE.sort.dedup.prefilter.bam METRICS_FILE=$EDIT_DIR/$SAMPLE.duplicates.txt
#fi

samtools view -h $EDIT_DIR/$SAMPLE.sort.dedup.prefilter.bam | perl -e 'while(<>){chomp;@tmp=split/\t/;if($tmp[5] !~ /(\d+)N(\d+)D(\d+)N/){print "$_\n"}}' - |
samtools view -Sb - > $EDIT_DIR/$SAMPLE.sort.dedup.bam
samtools index $EDIT_DIR/$SAMPLE.sort.dedup.bam


## SplitNCigarReads
# Standard GATK version for use with star changes all MAPQ=255 to Q=60 b/c 255 means "unknown" to GATK. TH outputs MAPQ: 0,1,3,50. No 255 apparent in TH MAPQ output.
# Compute: 3 hours w/4 threads / 1 h w/8 threads
java -jar $GATK_JAR -T SplitNCigarReads -R $REF -I $EDIT_DIR/$SAMPLE.sort.dedup.bam -o $EDIT_DIR/$SAMPLE.clipped.bam -U ALLOW_N_CIGAR_READS

## GATK base recalibration -- for this to work well, the alignment should be as correct as possible since it depends on information about ref mismatches for the recalibration. True rare variants will look like a seq error to the recalibration algorithm. False variants created by alignment mistakes will also look like seq error. 
# Recommended -nct = 8, mem = 4g, cluster nodes = 4

# step a = analyze
#Compute 2.75 hours w/4 threads / 1.3 h w/8 threads
java -jar $GATK_JAR -nct $THREADS -T BaseRecalibrator -R $REF -I $EDIT_DIR/$SAMPLE.clipped.bam --knownSites /sc/orga/projects/PBG/REFERENCES/hg19/dbsnp_135.hg19.reorder.vcf --knownSites /sc/orga/projects/PBG/REFERENCES/hg19/Mills_and_1000G_gold_standard.indels.hg19.sites.reorder.vcf -o $EDIT_DIR/$SAMPLE.recal_data.table 
    
# step b - generate report of effect of recalibration
# Compute: 4 hours w/4 threads / 2.2 horus w/8 threads   
java -jar $GATK_JAR -nct $THREADS -T BaseRecalibrator -R $REF -I $EDIT_DIR/$SAMPLE.clipped.bam --knownSites /sc/orga/projects/PBG/REFERENCES/hg19/dbsnp_135.hg19.reorder.vcf --knownSites /sc/orga/projects/PBG/REFERENCES/hg19/Mills_and_1000G_gold_standard.indels.hg19.sites.reorder.vcf -BQSR $EDIT_DIR/$SAMPLE.recal_data.table -o $EDIT_DIR/$SAMPLE.post_recal_data.table 
    
# step c - plot results
java -jar $GATK_JAR -T AnalyzeCovariates -R $REF -before $EDIT_DIR/$SAMPLE.recal_data.table -after $EDIT_DIR/$SAMPLE.post_recal_data.table -plots $EDIT_DIR/$SAMPLE.recalibration_plots.pdf

# step d - apply new Qs to data
# Compute: 5 hours w/4 threads / 2.4 hours w/8 threads
java -jar $GATK_JAR -nct $THREADS -T PrintReads -R $REF -I $EDIT_DIR/$SAMPLE.clipped.bam -BQSR $EDIT_DIR/$SAMPLE.recal_data.table -o $EDIT_DIR/$SAMPLE.recal_reads.bam 



## Finally, call variants and filter them
# Compute: 7 hours w/8 threads
java -jar $GATK_JAR -nct $THREADS -T HaplotypeCaller -R $REF -I $EDIT_DIR/$SAMPLE.recal_reads.bam -recoverDanglingHeads -dontUseSoftClippedBases -stand_call_conf 20.0 -stand_emit_conf 20.0 -o $EDIT_DIR/$SAMPLE.variants.vcf

# Compute: 0.75 hours
java -jar $GATK_JAR -T VariantFiltration -R $REF -V $EDIT_DIR/$SAMPLE.variants.vcf -window 35 -cluster 3 -filterName FS -filter "FS > 30.0" -filterName QD -filter "QD < 2.0" -o $EDIT_DIR/$SAMPLE.variants.flt.vcf

# Convert / compress
bcftools view -o $EDIT_DIR/$SAMPLE.variants.flt.bcf -O b -l 9 $EDIT_DIR/$SAMPLE.variants.flt.vcf

rm $EDIT_DIR/$SAMPLE.sort.dedup.bam $EDIT_DIR/$SAMPLE.sort.dedup.bam.bai $EDIT_DIR/$SAMPLE.clipped.bam $EDIT_DIR/$SAMPLE.clipped.bai $EDIT_DIR/$SAMPLE.variants.flt.vcf 