# Exploring Cranio data

##### Kristen K. Dang for Sage Bionetworks
##### Oct. 17, 2014

## Load libraries
```{r warning=FALSE,message=FALSE}
library(synapseClient)
synapseLogin()
setwd('~/Computing/cranio/')
```


Match data IDs with sample information.
```{r}
lookupEnt = synGet("syn2770057")
lookup = read.csv(getFileLocation(lookupEnt))

clinicalEnt = synGet("syn2731158")
clinical = read.csv(getFileLocation(clinicalEnt))
noMatch = which(is.na(match(lookup$UDF.Investigator.Sample.Name, clinical$Px.Code)))
lookup[noMatch,]

lookupRev = lookup
lookupRev$UDF.Investigator.Sample.Name = as.character(lookup$UDF.Investigator.Sample.Name)
lookupRev$UDF.Investigator.Sample.Name = replace(x=lookupRev$UDF.Investigator.Sample.Name, list=noMatch, values=c("1071", "1059", "1075"))
noMatch2 = which(is.na(match(lookupRev$UDF.Investigator.Sample.Name, clinical$Px.Code)))
rm(noMatch, noMatch2, lookup, lookupEnt)
```

Which ones are case/control?
```{r}
head(clinical)
levels(clinical$Sample.Type)

controls = which(clinical$Sample.Type == "Control")
write.table(x=lookupRev$Sample.Name[na.omit(match(clinical$SampleID[controls], lookupRev$UDF.Investigator.Sample.Name))], file="sampleList_controls.txt", quote=FALSE,row.names=FALSE,col.names=FALSE)

cases = which(clinical$Sample.Type != "Control")
write.table(x=lookupRev$Sample.Name[na.omit(match(clinical$SampleID[cases], lookupRev$UDF.Investigator.Sample.Name))], file="sampleList_cases.txt", quote=FALSE,row.names=FALSE,col.names=FALSE)
```