---
title: "covariate_analysis_peer"
author: "Kristen Dang"
date: "January 29, 2015"
output:
  html_document:
    fig_height: 9
    fig_width: 6
---

```{r}
# install.packages(pkgs = c("lubridate"),repos="http://cran.us.r-project.org", dependencies=TRUE)
# install.packages(pkgs = c("FactoMineR"),repos="http://cran.us.r-project.org", dependencies=TRUE)
# install.packages("corrgram")
# install.packages("devtools")
# require(devtools)
# install_github('brian-bot/rGithubClient', ref='dev')
# source('http://depot.sagebase.org/CRAN.R')
# pkgInstall(c("synapseClient"))

```

```{r message=FALSE,warning=FALSE}
library(peer)
library(corrgram)
library('rGithubClient')
token = read.delim('rGHclient_token.txt',header = FALSE)
setGithubToken(as.character(token[1,1]))

sageCode = getRepo(repository="kkdang/sage-data-analysis")
sourceRepoFile(sageCode, "scri_cran/cranio_common_routines.R")
proteinCoding_genes = getByBiotype()
```


Function to run PEER
```{r}
runPEER=function(inData,k_hidden=10,estMean=TRUE,covariates=NULL){
  #(NULL response means no error here), 
  
  #Now we can create the model object
  model = PEER()
  
  # Set the observed data,
  #The data matrix is assumed to have N rows and G columns, where N is the number of samples, and G is the number of genes.
  PEER_setPhenoMean(model,as.matrix(t(inData)))
  dim(PEER_getPhenoMean(model))
  
  # Say we want to infer K=10 hidden confounders,
  PEER_setNk(model,k_hidden)
  
  
  #PEER can automatically include an additional factor (covariate) to account for the mean expression. For most use cases, including the mean effect is likely to be a good choice. To active mean factors, use
  if (estMean){ 
    print('Adding Mean factor')
    PEER_setAdd_mean(model, TRUE) }
  
  #If there are measured experimental variables that may contribute to variability in the data, they can be included in the inference. The C observed covariates are assumed to be in a NxC matrix.
  if (!is.null(covariates)) { PEER_setCovariates(model, as.matrix(covariates)) }
  
  
  # Perform the inference.
  PEER_update(model)
  
  return(model)
}
```


Filter and convert metadata
```{r}
sourceRepoFile(sageCode, "scri_cran/process_metadata.R")
metadataFiltered = processMetadata(ver = 5,plot = FALSE)
```


Get PALX20 protein-coding dataset with outliers removed
```{r warning=FALSE, message=FALSE}
data.dge = generateDataObj('syn2820309')

outlierTable = synTableQuery('SELECT * FROM syn3354503')
outlierData = outlierTable@values
noOutliers.dge = data.dge[,-which(colnames(data.dge) %in% outlierData$minimalSet)]

## Remove samples that don't have seq data.
## Order the data in the same way for counts and metadata
metadataMatching = metadataFiltered[-which(!metadataFiltered$Px_Code %in% colnames(noOutliers.dge)),]
metadataMatching = metadataMatching[match(colnames(noOutliers.dge), metadataMatching$Px_Code),]
head(metadataMatching$Px_Code)
head(colnames(noOutliers.dge))

## Protein-coding genes, PALX=20%
b = as.list(rownames(noOutliers.dge))
strippedNames = sapply(b,function(x){unlist(strsplit(as.character(x), split = "[.]"))[1]})  
pc.dge = noOutliers.dge[which(strippedNames %in% proteinCoding_genes[,1]),]
pc_palo.dge = DGEList(counts = getCounts(pc.dge),group = pc.dge$samples$group)
pc_palx20.dge = filterByFractionPresent(pc_palo.dge,fraction=0.20,minCount=3)
pc_palx20.dge = calcNormFactors(pc_palx20.dge)
pc_palx20_data = voom(pc_palx20.dge, plot=FALSE)
tmp_fit = lmFit(pc_palx20_data,design=rep(1,ncol(pc_palx20_data)))
pc_palx20_res = residuals(tmp_fit,y = pc_palx20_data)
boxplot(pc_palx20_res,outline = FALSE,las=2)

```



PEER results and correlate factors with metadata
```{r}
### Model specification 

# Full model
fullDesign = model.matrix(~0+PCT_CORRECT_STRAND_READS+Age_mos.+Sex+PCT_INTRONIC_BASES,data = metadataMatching)

# Full model + LN2
fullDesign_pLN2= model.matrix(~0+Days_in_LN2+PCT_CORRECT_STRAND_READS+Age_mos.+Sex+PCT_INTRONIC_BASES,data = metadataMatching)

categFactors = c('Sex')
metaCategorical = c("Sex", "Sample_Type", "Initial_date_set_up", "Initial_date_freeze", "for_RNA_date_set_up", "for_RNA_date_plated", "for_RNA_date_harvest", "ScanDate", "Sample_Origin", "caseStatus", "SAMPLE","libraryBatch" )

cutoff = 0.05
```



Full design matrix, no mean
```{r fig.width=8, fig.height=8}
k = 25
numFactors = 5
pc_palx20_allcov.peer = runPEER(pc_palx20_res,covariates = fullDesign,estMean = FALSE,k_hidden = k)
plot(PEER_getAlpha(pc_palx20_allcov.peer)[(numFactors+1):(numFactors+k)],type = "o",ylab = "inverse variance of weights (precision)", xlab = "hidden factors")
factors = PEER_getX(pc_palx20_allcov.peer)
temp = calc_plot_PC_corr(in.pca = factors[,(numFactors+1):(numFactors+k)],inClinical=metadataMatching[,c(2:ncol(metadataMatching))],categorical = which(colnames(metadataMatching) %in% metaCategorical)-1,k = k)
weights = PEER_getW(pc_palx20_allcov.peer)
boxplot(weights[,(numFactors+1):(numFactors+k)], main = "full design, no mean", ylab = "weights")
```



Full design matrix, +LN2, no mean
```{r fig.width=8, fig.height=8}
k = 25
numFactors = 6
pc_palx20_allpLN2.peer = runPEER(pc_palx20_res,covariates = fullDesign_pLN2,estMean = FALSE,k_hidden = k)
plot(PEER_getAlpha(pc_palx20_allpLN2.peer)[(numFactors+1):(numFactors+k)],type = "o",ylab = "inverse variance of weights (precision)", xlab = "hidden factors")
factors = PEER_getX(pc_palx20_allpLN2.peer)
temp = calc_plot_PC_corr(in.pca = factors[,(numFactors+1):(numFactors+k)],inClinical=metadataMatching[,c(2:ncol(metadataMatching))],categorical = which(colnames(metadataMatching) %in% metaCategorical)-1,k = k)
weights = PEER_getW(pc_palx20_allpLN2.peer)
boxplot(weights[,(numFactors+1):(numFactors+k)], main = "full design, no mean", ylab = "weights")
```




Permuted dataset
```{r}
# Permutes sample order for each gene, breaking coexpression relationships between genes and breaking relationship between samples and metadata.
permute=function(inData){
  l = length(inData)
  x = sample(l,l, replace = FALSE)
  return(inData[x])
}

shuffle=function(inData,col=TRUE){
  if (col) { 
    # Suffles sample column order, breaking relationship with metadata. Gene relationships remain.
    s = sample(ncol(inData),ncol(inData),replace=FALSE)
    return(inData[,s])
  }
  else {
    s = sample(nrow(inData),nrow(inData),replace=FALSE)
    return(inData[s,])
  }
}

# Profile single permute
pc_palx20.permute = t(apply(pc_palx20_res,MARGIN = 1,permute))
k = 15
numFactors = 5
pc_palx20_permute.peer = runPEER(pc_palx20.permute,covariates = fullDesign,estMean = FALSE,k_hidden = k)
plot(PEER_getAlpha(pc_palx20_permute.peer)[(numFactors+1):(numFactors+k)],type = "o",ylab = "inverse variance of weights (precision)", xlab = "hidden factors")
factors = PEER_getX(pc_palx20_permute.peer)
temp = calc_plot_PC_corr(in.pca = factors[,(numFactors+1):(numFactors+k)],inClinical=metadataMatching[,c(2:ncol(metadataMatching))],categorical = which(colnames(metadataMatching) %in% metaCategorical)-1,k = k)
weights = PEER_getW(pc_palx20_permute.peer)
boxplot(weights[,(numFactors+1):(numFactors+k)], main = "full design, no mean", ylab = "weights")


# profile single shuffle
pc_palx20.shuffle = shuffle(pc_palx20_res)
k = 15
numFactors = 5
pc_palx20_shuffle.peer = runPEER(pc_palx20.shuffle,covariates = fullDesign,estMean = FALSE,k_hidden = k)
plot(PEER_getAlpha(pc_palx20_shuffle.peer)[(numFactors+1):(numFactors+k)],type = "o",ylab = "inverse variance of weights (precision)", xlab = "hidden factors")
factors = PEER_getX(pc_palx20_shuffle.peer)
temp = calc_plot_PC_corr(in.pca = factors[,(numFactors+1):(numFactors+k)],inClinical=metadataMatching[,c(2:ncol(metadataMatching))],categorical = which(colnames(metadataMatching) %in% metaCategorical)-1,k = k)
weights = PEER_getW(pc_palx20_shuffle.peer)
boxplot(weights[,(numFactors+1):(numFactors+k)], main = "full design, no mean", ylab = "weights")
```


Compare several random permutes to actual
```{r}
# k = 25
# numFactors = 5
# iterations = 100
# collectedPrecision = matrix(NA,nrow = k+numFactors,ncol=iterations)
# for (i in 1:iterations){
#   pc_palx20.permute = t(apply(pc_palx20_res,MARGIN = 1,permute))
#   pc_palx20_permute.peer = runPEER(pc_palx20.permute,covariates = fullDesign,estMean = FALSE,k_hidden = k)
#   collectedPrecision[,i] = PEER_getAlpha(pc_palx20_permute.peer)
# }
# 
# plot(collectedPrecision[(numFactors+1):(numFactors+k),1], type = "l", ylim = range(0,12), ylab = "precision", main = "permuted datasets vs actual", xlab = "factors")
# for (i in 2:14){
#   lines(collectedPrecision[(numFactors+1):(numFactors+k),i], type = "l")
# }
# lines(PEER_getAlpha(pc_palx20_allcov.peer)[(numFactors+1):(numFactors+k)],type = "o",ylab = "inverse variance of weights (precision)", xlab = "hidden factors", col = "orange")
```





```{r}
# posterior mean of the inferred confounders (NxK matrix)
# factors = PEER_getX(model)
# dim(factors)
# 
# # their weights (GxK matrix),
# weights = PEER_getW(model)
# dim(weights)
# 
# # precision (inverse variance) of the weights (Kx1 matrix),
# precision = PEER_getAlpha(model)
# dim(precision)
# 
# # residual dataset (NxG matrix)
# residuals = PEER_getResiduals(model)
# dim(residuals)

loadToSynapse=function(inPEER,modelName){
  newFileName = paste("Latent_factors_", modelName, ".csv", sep = "")
  write.csv(PEER_getX(inPEER),file=newFileName,quote=FALSE)
  factorsEntity = File(path=newFileName, parentId="syn2820780")
  factorsEntity = synStore(factorsEntity)
  newFileName = paste("residuals_", modelName, ".csv", sep = "")
  write.csv(PEER_getResiduals(inPEER),file=newFileName,quote=FALSE)
  residEntity = File(path=newFileName, parentId="syn2820780")
  residEntity = synStore(residEntity)

}

#loadToSynapse(pc_palx20_allcov.peer,'fullModel_nomean')
#loadToSynapse(pc_palx20_allpLN2.peer,'fullModel_pLN2_nomean')
```
