---
title: "gender_check.Rmd"
author: "Kristen Dang"
date: "March 2, 2015"
output: html_document
---

```{r message=FALSE,warning=FALSE}
library('githubr')
source('/Users/kkdang/Computing/rgithubclient_authenticate.R')
sourceRepoFile(sageCode, 'scri_cran/cranio_common_routines.R')
sourceRepoFile(sageCode, 'biomart_fxns.R')
```

Get the metadata
```{r}
metadataTable = synTableQuery('SELECT Sample_ID,Sex FROM syn7486948')
head(metadataTable@values)
dim(metadataTable@values)
```



```{r}
Ygenes = getBM(attributes=c("ensembl_gene_id"),filters="chromosome_name",values="Y", mart=Hs)


dataEnt = read.delim(getFileLocation(synGet('syn7477102')), row.names = 1, header = TRUE)
lookupTable = synTableQuery('SELECT * FROM syn7477113')
head(lookupTable@values)

newNames = lookupTable@values$Investigator_Sample_Name[match(colnames(dataEnt), paste("X",lookupTable@values$Sample_Name, sep = ""))]
colnames(dataEnt) = newNames

data.dge = DGEList(counts=dataEnt,remove.zeros=TRUE)
palx5.dge = filterByFractionPresent(data.dge,fraction = 0.05)

setdiff(colnames(data.dge), metadataTable@values$Sample_ID)
setdiff(metadataTable@values$Sample_ID, colnames(data.dge))
```

Compare estimated to reported sex
```{r}
YgeneCounts = palx5.dge[which(rownames(palx5.dge) %in% Ygenes[,1]),]
YgeneFraction = colSums(getCounts(YgeneCounts))/YgeneCounts$samples$lib.size
hist(YgeneFraction, main = "fraction of counts from chrY genes")
hist(YgeneFraction,xlim = range(1e-5,5e-4),breaks = 2000)

predictedMales = names(which(YgeneFraction > 1.5e-4))
reportedMales = as.character(metadataTable@values$Sample_ID[metadataTable@values$Sex == "M"])
print("What samples are reported Males but chrY counts suggests female?")
setdiff(reportedMales, predictedMales)
print("What samples are predicted Males according to chrY counts but reported Females?")
setdiff(predictedMales, reportedMales)
changeMtoF = setdiff(reportedMales, predictedMales)
YgeneFraction[which(names(YgeneFraction)%in% changeMtoF)]
hist(YgeneFraction,xlim = range(1e-7,5e-5),breaks = 200)

predictedFemales = setdiff(colnames(palx5.dge), predictedMales)
reportedFemales = as.character(metadataTable@values$Sample_ID[metadataTable@values$Sex == "F"])
print("What samples are predicted Female according to chrY counts but reported Male?")
setdiff(predictedFemales, reportedFemales)
print("What samples are reported Female but predicted Male?")
setdiff(reportedFemales,predictedFemales)

```


Correct the metadata file
```{r}
# temp = read.delim(getFileLocation(metadataEnt),header = TRUE)
# temp$Sex[which(temp$Px_Code %in% changeMtoF)] = as.factor("F")
# write.table(temp,file=getFileLocation(metadataEnt),append = FALSE,quote = FALSE,sep = "\t",row.names = FALSE)
# metadataEnt = synStore(metadataEnt)
```
